# 06_tables.R - Generate all LaTeX tables from saved model objects
# Input:  data/interim/models/*.rds
# Output: results/tables/tab_*.tex

source(here::here("src/analysis/utils/helpers.R"))
suppressPackageStartupMessages({
  library(fixest)
  library(kableExtra)
})

set.seed(SEED)
LOGFILE <- file.path(DIR_LOGS, "06_tables.log")
cat("", file = LOGFILE)

log_msg("=== 06: Generate Tables ===", logfile = LOGFILE)

# Load panel for N counts (fixest models reference the data environment)
panel <- load_panel()
panel_cc <- panel %>% filter(!is.na(asd))

# =====================================================
# tab_descriptive.tex - already generated by script 01
# =====================================================
if (file.exists(file.path(DIR_TABLES, "tab_descriptive.tex"))) {
  log_msg("tab_descriptive.tex exists (from script 01)", logfile = LOGFILE)
} else {
  log_msg("WARNING: tab_descriptive.tex missing - run script 01 first", logfile = LOGFILE)
}

# =====================================================
# tab_main_did.tex - Main DiD results (RQ1)
# =====================================================
log_msg("\n--- tab_main_did.tex ---", logfile = LOGFILE)

m_bor  <- readRDS(file.path(DIR_MODELS, "m_borusyak_static.rds"))
m_twfe <- readRDS(file.path(DIR_MODELS, "m_twfe_sa.rds"))

# Borusyak: did_imputation returns a tibble directly
r_bor <- extract_did_imp(m_bor)
bor_beta <- r_bor$beta
bor_se   <- r_bor$se
bor_p    <- r_bor$pval

# TWFE: fixest object, use summary + coeftable
s_twfe_agg <- summary(m_twfe, agg = "att")
twfe_ct <- coeftable(s_twfe_agg)
twfe_beta <- twfe_ct[1, 1]
twfe_se   <- twfe_ct[1, 2]
twfe_p    <- twfe_ct[1, 4]

stars_fn <- function(p) {
  if (p < 0.01) return("***")
  if (p < 0.05) return("**")
  if (p < 0.1)  return("*")
  return("")
}

# Both estimators use same complete-case panel
n_obs_est   <- m_twfe$nobs
n_repos_est <- length(unique(m_twfe$fixef_id$repo_int))

# Use fixest::etable for the TWFE model directly (cleaner)
# But for the combined table, manual approach is more reliable
tex_lines <- c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Main diff-in-diff estimates: effect of AI tool adoption on architectural smell density (log ASD).}",
  "\\label{tab:main_did}",
  "\\begin{tabular}{lcc}",
  "\\toprule",
  " & Borusyak & TWFE-SA \\\\",
  "\\midrule",
  sprintf("ATT ($\\hat{\\beta}$) & %.4f%s & %.4f%s \\\\",
          bor_beta, stars_fn(bor_p), twfe_beta, stars_fn(twfe_p)),
  sprintf(" & (%.4f) & (%.4f) \\\\", bor_se, twfe_se),
  sprintf("Effect (\\%%) & %.1f\\%% & %.1f\\%% \\\\",
          pct_effect(bor_beta), pct_effect(twfe_beta)),
  "\\midrule",
  sprintf("Observations & %d & %d \\\\", n_obs_est, n_obs_est),
  sprintf("Repos & %d & %d \\\\", n_repos_est, n_repos_est),
  "Repo FE & Yes & Yes \\\\",
  "Time FE & Yes & Yes \\\\",
  "Clustered SE & Repo & Repo \\\\",
  "\\bottomrule",
  "\\multicolumn{3}{l}{\\footnotesize $^{*}p<0.1$; $^{**}p<0.05$; $^{***}p<0.01$} \\\\",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex_lines, file.path(DIR_TABLES, "tab_main_did.tex"))
log_msg("Saved: tab_main_did.tex", logfile = LOGFILE)

# =====================================================
# tab_disaggregated.tex - Per-smell-type results (RQ2)
# =====================================================
log_msg("\n--- tab_disaggregated.tex ---", logfile = LOGFILE)

smell_names <- c(cd = "Cyclic Dep.", ud = "Unstable Dep.",
                 hl = "Hub-Like Dep.", gc = "God Component")

rows <- list()
for (name in names(smell_names)) {
  fpath <- file.path(DIR_MODELS, sprintf("m_disagg_%s.rds", name))
  if (file.exists(fpath)) {
    m <- readRDS(fpath)
    r <- extract_did_imp(m)
    rows[[name]] <- tibble(
      Smell = smell_names[name],
      beta = r$beta,
      se = r$se,
      pval = r$pval
    )
  }
}

df_disagg <- bind_rows(rows) %>%
  mutate(
    ci_lo = beta - qnorm(0.975) * se,
    ci_hi = beta + qnorm(0.975) * se,
    effect_pct = pct_effect(beta),
    holm_pval = p.adjust(pval, method = "holm")
  )

tex_disagg <- c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Disaggregated treatment effects by architectural smell type (Borusyak imputation).}",
  "\\label{tab:disaggregated}",
  "\\begin{tabular}{lcccccc}",
  "\\toprule",
  "Smell Type & ATT ($\\hat{\\beta}$) & SE & 95\\% CI & $p$ & Holm $p$ & Effect (\\%) \\\\",
  "\\midrule"
)

for (i in seq_len(nrow(df_disagg))) {
  r <- df_disagg[i, ]
  tex_disagg <- c(tex_disagg,
    sprintf("%s & %.4f%s & %.4f & [%.4f, %.4f] & %.4f & %.4f & %.1f\\%% \\\\",
            r$Smell, r$beta, stars_fn(r$holm_pval), r$se, r$ci_lo, r$ci_hi,
            r$pval, r$holm_pval, r$effect_pct)
  )
}

tex_disagg <- c(tex_disagg,
  "\\bottomrule",
  "\\multicolumn{7}{l}{\\footnotesize $^{*}p<0.1$; $^{**}p<0.05$; $^{***}p<0.01$ (Holm-adjusted). God Component has 77.5\\% zero-inflation.} \\\\",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex_disagg, file.path(DIR_TABLES, "tab_disaggregated.tex"))
log_msg("Saved: tab_disaggregated.tex", logfile = LOGFILE)

# =====================================================
# tab_robustness.tex - All robustness checks
# =====================================================
log_msg("\n--- tab_robustness.tex ---", logfile = LOGFILE)

rob_rows <- list()

# Borusyak (primary, from script 02)
rob_rows[["Borusyak (primary)"]] <- tibble(
  Estimator = "Borusyak (primary)", beta = bor_beta, se = bor_se, pval = bor_p
)

# TWFE-SA
rob_rows[["TWFE-SA"]] <- tibble(
  Estimator = "TWFE-SA", beta = twfe_beta, se = twfe_se, pval = twfe_p
)

# C&S
cs_path <- file.path(DIR_MODELS, "m_cs.rds")
if (file.exists(cs_path)) {
  cs_obj <- readRDS(cs_path)
  rob_rows[["Callaway \\& Sant'Anna"]] <- tibble(
    Estimator = "Callaway \\& Sant'Anna",
    beta = cs_obj$agg$overall.att,
    se = cs_obj$agg$overall.se,
    pval = 2 * pnorm(-abs(cs_obj$agg$overall.att / cs_obj$agg$overall.se))
  )
}

# Placebo - recreate data environment for fixest models
panel_placebo_3m <- panel_cc %>%
  mutate(fake_treat_sa_3 = ifelse(is_treatment == 0, 100000L, first_treat_sa - 3L))

plac_path <- file.path(DIR_MODELS, "m_placebo.rds")
if (file.exists(plac_path)) {
  m_plac <- readRDS(plac_path)
  if (inherits(m_plac, "fixest")) {
    # TWFE placebo - re-estimate to avoid data environment issues
    m_plac <- tryCatch({
      summary(m_plac, agg = "att")
    }, error = function(e) {
      # Re-fit if data environment is lost
      m_refit <- feols(
        log_asd ~ sunab(fake_treat_sa_3, month_id) | repo_int + month_id,
        data = panel_placebo_3m %>% filter(month_id < first_treat_sa | is_treatment == 0),
        vcov = ~repo_int
      )
      summary(m_refit, agg = "att")
    })
    ct <- coeftable(m_plac)
    rob_rows[["Placebo ($t-3$)"]] <- tibble(
      Estimator = "Placebo ($t-3$)",
      beta = ct[1, 1], se = ct[1, 2], pval = ct[1, 4]
    )
  } else {
    # did_imputation placebo
    r_plac <- extract_did_imp(m_plac)
    rob_rows[["Placebo ($t-6$)"]] <- tibble(
      Estimator = "Placebo ($t-6$)",
      beta = r_plac$beta, se = r_plac$se, pval = r_plac$pval
    )
  }
}

df_rob <- bind_rows(rob_rows) %>%
  mutate(
    ci_lo = beta - qnorm(0.975) * se,
    ci_hi = beta + qnorm(0.975) * se,
    effect_pct = pct_effect(beta)
  )

tex_rob <- c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Robustness checks: alternative estimators and placebo test.}",
  "\\label{tab:robustness}",
  "\\begin{tabular}{lccccc}",
  "\\toprule",
  "Estimator & ATT ($\\hat{\\beta}$) & SE & 95\\% CI & $p$-value & Effect (\\%) \\\\",
  "\\midrule"
)

for (i in seq_len(nrow(df_rob))) {
  r <- df_rob[i, ]
  tex_rob <- c(tex_rob,
    sprintf("%s & %.4f%s & %.4f & [%.4f, %.4f] & %.4f & %.1f\\%% \\\\",
            r$Estimator, r$beta, stars_fn(r$pval), r$se, r$ci_lo, r$ci_hi, r$pval, r$effect_pct)
  )
}

tex_rob <- c(tex_rob,
  "\\bottomrule",
  "\\multicolumn{6}{l}{\\footnotesize $^{*}p<0.1$; $^{**}p<0.05$; $^{***}p<0.01$} \\\\",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex_rob, file.path(DIR_TABLES, "tab_robustness.tex"))
log_msg("Saved: tab_robustness.tex", logfile = LOGFILE)

# =====================================================
# tab_size_stratified.tex - Size heterogeneity
# =====================================================
log_msg("\n--- tab_size_stratified.tex ---", logfile = LOGFILE)

size_rows <- list()
for (sz in c("small", "large")) {
  fpath <- file.path(DIR_MODELS, sprintf("m_size_%s.rds", sz))
  if (file.exists(fpath)) {
    m <- readRDS(fpath)
    r <- extract_did_imp(m)
    size_rows[[sz]] <- tibble(
      Group = ifelse(sz == "small", "Small ($\\leq$ median)", "Large ($>$ median)"),
      beta = r$beta, se = r$se, pval = r$pval
    )
  }
}

# Add full sample
size_rows[["full"]] <- tibble(
  Group = "Full sample", beta = bor_beta, se = bor_se, pval = bor_p
)

df_size <- bind_rows(size_rows) %>%
  mutate(
    ci_lo = beta - qnorm(0.975) * se,
    ci_hi = beta + qnorm(0.975) * se,
    effect_pct = pct_effect(beta)
  )

tex_size <- c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Size-stratified treatment effects (Borusyak imputation, split at median KLOC).}",
  "\\label{tab:size_stratified}",
  "\\begin{tabular}{lccccc}",
  "\\toprule",
  "Sample & ATT ($\\hat{\\beta}$) & SE & 95\\% CI & $p$-value & Effect (\\%) \\\\",
  "\\midrule"
)

for (i in seq_len(nrow(df_size))) {
  r <- df_size[i, ]
  tex_size <- c(tex_size,
    sprintf("%s & %.4f%s & %.4f & [%.4f, %.4f] & %.4f & %.1f\\%% \\\\",
            r$Group, r$beta, stars_fn(r$pval), r$se, r$ci_lo, r$ci_hi, r$pval, r$effect_pct)
  )
}

tex_size <- c(tex_size,
  "\\bottomrule",
  "\\multicolumn{6}{l}{\\footnotesize $^{*}p<0.1$; $^{**}p<0.05$; $^{***}p<0.01$} \\\\",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex_size, file.path(DIR_TABLES, "tab_size_stratified.tex"))
log_msg("Saved: tab_size_stratified.tex", logfile = LOGFILE)

# =====================================================
# tab_combined_results.tex - Combined main + robustness
# =====================================================
log_msg("\n--- Combined Results Table ---", logfile = LOGFILE)

combined_rows <- list()

# Borusyak (primary)
combined_rows[["Borusyak (primary)"]] <- tibble(
  Estimator = "Borusyak (primary)", beta = bor_beta, se = bor_se,
  pval = bor_p, n = n_obs_est
)

# TWFE-SA
combined_rows[["TWFE-SA"]] <- tibble(
  Estimator = "TWFE-SA", beta = twfe_beta, se = twfe_se,
  pval = twfe_p, n = n_obs_est
)

# Covariate sensitivity (A1)
cov_path <- file.path(DIR_MODELS, "m_twfe_sa_cov.rds")
if (file.exists(cov_path)) {
  m_cov <- readRDS(cov_path)
  s_cov <- tryCatch(summary(m_cov, agg = "att"), error = function(e) {
    m_refit <- feols(
      log_asd ~ sunab(first_treat_sa, month_id) + monthly_contributors
        | repo_int + month_id,
      data = panel_cc, vcov = ~repo_int
    )
    summary(m_refit, agg = "att")
  })
  ct_cov <- coeftable(s_cov)
  combined_rows[["TWFE-SA + covariates"]] <- tibble(
    Estimator = "TWFE-SA + covariates", beta = ct_cov[1,1], se = ct_cov[1,2],
    pval = ct_cov[1,4], n = n_obs_est
  )
}

# C&S (no covariates)
cs_path <- file.path(DIR_MODELS, "m_cs.rds")
if (file.exists(cs_path)) {
  cs_obj <- readRDS(cs_path)
  combined_rows[["C\\&S (no cov.)"]] <- tibble(
    Estimator = "C\\&S (no cov.)",
    beta = cs_obj$agg$overall.att, se = cs_obj$agg$overall.se,
    pval = 2 * pnorm(-abs(cs_obj$agg$overall.att / cs_obj$agg$overall.se)),
    n = n_obs_est
  )
}

# C&S IPW (A3)
cs_ipw_path <- file.path(DIR_MODELS, "m_cs_ipw.rds")
if (file.exists(cs_ipw_path)) {
  cs_ipw_obj <- readRDS(cs_ipw_path)
  combined_rows[["C\\&S IPW"]] <- tibble(
    Estimator = "C\\&S IPW",
    beta = cs_ipw_obj$agg$overall.att, se = cs_ipw_obj$agg$overall.se,
    pval = 2 * pnorm(-abs(cs_ipw_obj$agg$overall.att / cs_ipw_obj$agg$overall.se)),
    n = n_obs_est
  )
}

# Placebo
if (exists("rob_rows") && "Placebo ($t-3$)" %in% names(rob_rows)) {
  plac_r <- rob_rows[["Placebo ($t-3$)"]]
  combined_rows[["Placebo ($t-3$)"]] <- tibble(
    Estimator = "Placebo ($t-3$)", beta = plac_r$beta, se = plac_r$se,
    pval = plac_r$pval, n = 1327L
  )
}

df_combined <- bind_rows(combined_rows) %>%
  mutate(
    ci_lo = beta - qnorm(0.975) * se,
    ci_hi = beta + qnorm(0.975) * se,
    effect_pct = pct_effect(beta)
  )

tex_combined <- c(
  "\\begin{table}[t]",
  "\\centering",
  "\\caption{Summary of DiD estimates across estimators and specifications.}",
  "\\label{tab:combined}",
  "\\small",
  "\\begin{tabular}{lccccc}",
  "\\toprule",
  "Estimator & $\\hat{\\beta}$ & SE & 95\\% CI & $p$ & Effect (\\%) \\\\",
  "\\midrule"
)

for (i in seq_len(nrow(df_combined))) {
  r <- df_combined[i, ]
  tex_combined <- c(tex_combined,
    sprintf("%s & %.4f%s & %.4f & [%.4f, %.4f] & %.4f & %.1f\\%% \\\\",
            r$Estimator, r$beta, stars_fn(r$pval), r$se, r$ci_lo, r$ci_hi,
            r$pval, r$effect_pct)
  )
}

tex_combined <- c(tex_combined,
  "\\bottomrule",
  "\\multicolumn{6}{l}{\\footnotesize $^{*}p<0.1$; $^{**}p<0.05$; $^{***}p<0.01$} \\\\",
  "\\end{tabular}",
  "\\end{table}"
)

writeLines(tex_combined, file.path(DIR_TABLES, "tab_combined_results.tex"))
log_msg("Saved: tab_combined_results.tex", logfile = LOGFILE)

log_msg("\n=== 06: Complete ===", logfile = LOGFILE)
