# 07_figures.R - Generate all publication figures from saved model objects
# Input:  data/interim/models/*.rds, data/processed/panel_monthly.csv
# Output: results/figures/fig_*.pdf

source(here::here("src/analysis/utils/helpers.R"))
suppressPackageStartupMessages({
  library(fixest)
  library(didimputation)
  library(patchwork)
})

set.seed(SEED)
LOGFILE <- file.path(DIR_LOGS, "07_figures.log")
cat("", file = LOGFILE)

log_msg("=== 07: Generate Figures ===", logfile = LOGFILE)

# Color palette (colorblind-friendly)
COL_TREAT <- "#2166AC"
COL_CTRL  <- "#B2182B"
COL_SMALL <- "#2166AC"
COL_LARGE <- "#D6604D"

# --- Load panel for distributions ---
panel <- load_panel()
panel_cc <- panel %>% filter(!is.na(asd))

# =====================================================
# fig_distributions.pdf - already generated by script 01
# =====================================================
if (file.exists(file.path(DIR_FIGURES, "fig_distributions.pdf"))) {
  log_msg("fig_distributions.pdf exists (from script 01)", logfile = LOGFILE)
} else {
  log_msg("WARNING: fig_distributions.pdf missing", logfile = LOGFILE)
}

# =====================================================
# fig_rq2_forest_plot.pdf - Forest plot for smell types
# =====================================================
log_msg("\n--- fig_rq2_forest_plot.pdf ---", logfile = LOGFILE)

smell_names <- c(cd = "Cyclic\nDependency", ud = "Unstable\nDependency",
                 hl = "Hub-Like\nDependency", gc = "God\nComponent")

forest_data <- list()
for (name in names(smell_names)) {
  fpath <- file.path(DIR_MODELS, sprintf("m_disagg_%s.rds", name))
  if (file.exists(fpath)) {
    m <- readRDS(fpath)
    r <- extract_did_imp(m)
    forest_data[[name]] <- tibble(
      smell = smell_names[name],
      smell_code = toupper(name),
      beta = r$beta,
      se = r$se,
      ci_lo = r$ci_lo,
      ci_hi = r$ci_hi,
      pval = r$pval
    )
  }
}

df_forest <- bind_rows(forest_data) %>%
  mutate(
    effect_pct = pct_effect(beta),
    ci_lo_pct = pct_effect(ci_lo),
    ci_hi_pct = pct_effect(ci_hi),
    holm_pval = p.adjust(pval, method = "holm"),
    sig = ifelse(holm_pval < 0.05, "Significant (Holm)", "Not significant")
  )

p_forest <- ggplot(df_forest, aes(x = effect_pct, y = fct_reorder(smell, effect_pct))) +
  geom_vline(xintercept = 0, linetype = "dashed", color = "gray50") +
  geom_errorbarh(aes(xmin = ci_lo_pct, xmax = ci_hi_pct), height = 0.25, linewidth = 0.7) +
  geom_point(aes(shape = sig), size = 3, fill = COL_TREAT) +
  scale_shape_manual(values = c("Significant (Holm)" = 16, "Not significant" = 21)) +
  labs(x = "Treatment Effect on Smell Density (%)", y = NULL,
       title = "Treatment Effect by Architectural Smell Type",
       shape = NULL) +
  theme_paper() +
  theme(legend.position = "bottom")

save_fig(p_forest, "fig_rq2_forest_plot.pdf")
log_msg("Saved: fig_rq2_forest_plot.pdf", logfile = LOGFILE)

# =====================================================
# fig_rq3_event_study.pdf - Main event study
# =====================================================
log_msg("\n--- fig_rq3_event_study.pdf ---", logfile = LOGFILE)

m_es <- readRDS(file.path(DIR_MODELS, "m_es_borusyak.rds"))

# Load SA event study for overlay
m_es_sa <- readRDS(file.path(DIR_MODELS, "m_es_sa.rds"))
sa_ct <- coeftable(m_es_sa)
sa_df <- tibble(
  term = rownames(sa_ct),
  estimate = sa_ct[, 1],
  std.error = sa_ct[, 2]
) %>%
  mutate(
    h = as.integer(stringr::str_extract(term, "-?\\d+$")),
    effect_pct = pct_effect(estimate)
  ) %>%
  filter(!is.na(h)) %>%
  arrange(h)

# did_imputation returns a tibble directly with term, estimate, std.error, conf.low, conf.high
es_df <- m_es %>%
  mutate(
    h = as.integer(term),
    effect_pct = pct_effect(estimate),
    ci_lo_pct = pct_effect(conf.low),
    ci_hi_pct = pct_effect(conf.high)
  ) %>%
  arrange(h)

p_es <- ggplot(es_df, aes(x = h, y = effect_pct)) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
  geom_vline(xintercept = -0.5, linetype = "dotted", color = "red", alpha = 0.7) +
  geom_ribbon(aes(ymin = ci_lo_pct, ymax = ci_hi_pct), alpha = 0.15, fill = COL_TREAT) +
  geom_line(color = COL_TREAT, linewidth = 0.8) +
  geom_point(color = COL_TREAT, size = 2.5) +
  # SA overlay (grey dashed)
  geom_line(data = sa_df, aes(x = h, y = effect_pct),
            color = "grey50", linewidth = 0.5, linetype = "dashed") +
  geom_point(data = sa_df, aes(x = h, y = effect_pct),
             shape = 1, color = "grey50", size = 2) +
  annotate("text", x = -0.7, y = max(es_df$ci_hi_pct, na.rm = TRUE) * 0.9,
           label = "Adoption", color = "red", hjust = 1, size = 3.5, fontface = "italic") +
  scale_x_continuous(breaks = seq(-6, 6)) +
  labs(x = "Months Relative to AI Tool Adoption",
       y = "Effect on ASD (%)",
       title = "Event Study: Architectural Smell Density",
       subtitle = "Borusyak (solid blue) vs. Sun & Abraham (dashed grey)") +
  theme_paper()

save_fig(p_es, "fig_rq3_event_study.pdf")
log_msg("Saved: fig_rq3_event_study.pdf", logfile = LOGFILE)

# =====================================================
# fig_size_event_study.pdf - Event study by size
# =====================================================
log_msg("\n--- fig_size_event_study.pdf ---", logfile = LOGFILE)

size_es_data <- list()
for (sz in c("small", "large")) {
  fpath <- file.path(DIR_MODELS, sprintf("m_es_%s.rds", sz))
  if (file.exists(fpath)) {
    m <- readRDS(fpath)
    size_es_data[[sz]] <- m %>%
      mutate(
        h = as.integer(term),
        size_group = ifelse(sz == "small", "Small repos", "Large repos"),
        effect_pct = pct_effect(estimate),
        ci_lo_pct = pct_effect(conf.low),
        ci_hi_pct = pct_effect(conf.high)
      )
  }
}

if (length(size_es_data) == 2) {
  df_size_es <- bind_rows(size_es_data) %>% arrange(size_group, h)

  p_size_es <- ggplot(df_size_es, aes(x = h, y = effect_pct, color = size_group, fill = size_group)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_vline(xintercept = -0.5, linetype = "dotted", color = "red", alpha = 0.7) +
    geom_ribbon(aes(ymin = ci_lo_pct, ymax = ci_hi_pct), alpha = 0.1, color = NA) +
    geom_line(linewidth = 0.8) +
    geom_point(size = 2.5) +
    scale_color_manual(values = c("Small repos" = COL_SMALL, "Large repos" = COL_LARGE)) +
    scale_fill_manual(values = c("Small repos" = COL_SMALL, "Large repos" = COL_LARGE)) +
    scale_x_continuous(breaks = seq(-6, 6)) +
    labs(x = "Months Relative to AI Tool Adoption",
         y = "Effect on ASD (%)",
         title = "Event Study by Repository Size",
         color = NULL, fill = NULL) +
    theme_paper()

  save_fig(p_size_es, "fig_size_event_study.pdf")
  log_msg("Saved: fig_size_event_study.pdf", logfile = LOGFILE)
} else {
  log_msg("WARNING: Missing size-stratified event study models", logfile = LOGFILE)
}

# =====================================================
# fig_placebo.pdf - Placebo event study
# =====================================================
log_msg("\n--- fig_placebo.pdf ---", logfile = LOGFILE)

plac_path <- file.path(DIR_MODELS, "m_es_placebo.rds")
if (file.exists(plac_path)) {
  m_plac <- readRDS(plac_path)

  if (inherits(m_plac, "fixest")) {
    # TWFE placebo - extract coefficients from fixest object
    ct <- coeftable(m_plac)
    plac_df <- tibble(
      term = rownames(ct),
      estimate = ct[, 1],
      std.error = ct[, 2]
    ) %>%
      mutate(
        h = as.integer(stringr::str_extract(term, "-?\\d+$")),
        effect_pct = pct_effect(estimate),
        ci_lo_pct = pct_effect(estimate - qnorm(0.975) * std.error),
        ci_hi_pct = pct_effect(estimate + qnorm(0.975) * std.error)
      ) %>%
      filter(!is.na(h)) %>%
      arrange(h)
  } else {
    # did_imputation placebo
    plac_df <- m_plac %>%
      mutate(
        h = as.integer(term),
        effect_pct = pct_effect(estimate),
        ci_lo_pct = pct_effect(conf.low),
        ci_hi_pct = pct_effect(conf.high)
      ) %>%
      arrange(h)
  }

  p_placebo <- ggplot(plac_df, aes(x = h, y = effect_pct)) +
    geom_hline(yintercept = 0, linetype = "dashed", color = "gray50") +
    geom_vline(xintercept = -0.5, linetype = "dotted", color = "red", alpha = 0.7) +
    geom_ribbon(aes(ymin = ci_lo_pct, ymax = ci_hi_pct), alpha = 0.15, fill = "gray40") +
    geom_line(color = "gray40", linewidth = 0.8) +
    geom_point(color = "gray40", size = 2.5) +
    annotate("text", x = -0.7, y = max(plac_df$ci_hi_pct, na.rm = TRUE) * 0.9,
             label = "Fake adoption", color = "red", hjust = 1, size = 3.5, fontface = "italic") +
    labs(x = "Months Relative to Fake Adoption (t - 3)",
         y = "Effect on ASD (%)",
         title = "Placebo Test: Fake Adoption 3 Months Earlier") +
    theme_paper()

  save_fig(p_placebo, "fig_placebo.pdf")
  log_msg("Saved: fig_placebo.pdf", logfile = LOGFILE)
} else {
  log_msg("WARNING: Placebo event study model not found", logfile = LOGFILE)
}

log_msg("\n=== 07: Complete ===", logfile = LOGFILE)
